name: Erlang build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: valitydev/action-setup-thrift@v1

      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: "24"
          rebar3-version: "3.18"

      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt-cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            _build/default/rebar3_*_plt

      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 dialyzer
